apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onboarding-faucet.fullname" . }}
  labels:
    {{- include "onboarding-faucet.labels" . | nindent 4 }}
data:
  HOSTNAME: {{ .Values.config.HOSTNAME | quote }}
  PORT: {{ .Values.config.PORT | quote }}
  RPC_URL: {{ .Values.config.RPC_URL | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  
