{{- define "common.envFromRef.tpl" -}}
{{- if or (or (or (or (or (.Values.vars) (.Values.secretEnabled)) .Values.sealedSecrets) .Values.secretName) .Values.existingConfigMaps) .Values.existingSecrets -}}
envFrom:
{{- if .Values.vars }}
  - configMapRef:
      name: {{ template "common.robustName" .Release.Name }}
{{- end }}
{{- range .Values.existingSecrets }}
  - secretRef:
      name: {{ .name }}
      optional: {{ .optional | default false }}
{{- end }}
{{- range .Values.existingConfigMaps }}
  - configMapRef:
      name: {{ .name }}
      optional: {{ .optional | default false }}
{{- end }}
{{- if .Values.secretEnabled }}
  - secretRef:
      name: {{ include "common.robustName" $.Release.Name }}
{{- end }}
{{- if .Values.secretName }}
  - secretRef:
      name: {{ .Values.secretName }}
{{- end }}
{{- if .Values.sealedSecrets }}
  - secretRef:
      name: {{ template "common.robustName" .Release.Name }}
{{- end }}
{{- end }}
{{- end }}