apiVersion: v2
appVersion: latest
name: ethexporter
version: 0.2.0
description: ETHexporter Helm chart for Kubernetes
home: https://www.ethswarm.org
icon: https://docs.ethswarm.org/img/swarm-logo-2.svg
keywords:
  - blockchain
  - ethereum
  - prometheus
  - exporter
maintainers:
  - name: darkobas2
    email: darkobas@ethswarm.org
sources:
  - https://github.com/ethersphere/ethexporter
type: application
