{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bee-overlay-exporter.serviceAccountName" . }}
  labels:
    {{- include "bee-overlay-exporter.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bee-overlay-exporter.fullname" . }}
  labels:
    {{- include "bee-overlay-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bee-overlay-exporter.fullname" . }}
  labels:
    {{- include "bee-overlay-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bee-overlay-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bee-overlay-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
