apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "beekeeper.fullname" . }}
  labels:
    {{- include "beekeeper.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  concurrencyPolicy: "{{ .Values.cronJob.concurrencyPolicy }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "beekeeper.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: BK_NAMESPACE
                  value: "{{ .Values.cronJob.namespace }}"
                - name: BK_BOOTNODE_COUNT
                  value: "{{ .Values.cronJob.bootNodeCount }}"
                - name: BK_NODE_COUNT
                  value: "{{ .Values.cronJob.nodeCount }}"
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
