{{- if and .Values.serviceAccount.create .Values.serviceAccount.createRole -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "beekeeper.serviceAccountName" . }}
  labels:
{{ include "beekeeper.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - services
    - events
    - namespaces
  verbs: ["*"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["create", "get", "list", "watch", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch","update", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["*"]
- apiGroups: ["pingcap.com"]
  resources:
  - podchaos
  - networkchaos
  - iochaos
  - timechaos
  - kernelchaos
  - stresschaos
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "beekeeper.serviceAccountName" . }}
  labels:
{{ include "beekeeper.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "beekeeper.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "beekeeper.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}