{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "beekeeper.serviceAccountName" . }}
  labels:
{{ include "beekeeper.labels" . | nindent 4 }}
{{- end -}}