{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-local-disk-provisioner.serviceAccountName" . }}
  labels:
    {{- include "eks-local-disk-provisioner.labels" . | nindent 4 }}
{{- end -}}
