apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: beeport-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeport-proxy
  template:
    metadata:
      labels:
        app: beeport-proxy
    spec:
      containers:
      - name: beeport-proxy
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: CORS_ORIGIN
          value: {{ .Values.env.corsOrigin }}
        - name: PORT
          value: {{ .Values.env.port | quote }}
        - name: PROXY_TARGET
          value: {{ .Values.env.proxyTarget }}
