{{- if .Values.addressesTxt.enabled }}
{{- if not .Values.addressesTxt.existingConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tokenexporter.fullname" . }}-addresses
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tokenexporter.labels" . | nindent 4 }}
data:
  addresses.txt: {{ .Values.addressesTxt.addresses | quote }}
{{- end }}
{{- end }}
