{{- include "common.configmap.tpl" . -}}
{{- define "nginx.configMapTemplate" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config-template
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  default.conf.template: |
    server {
        listen ${NGINX_PORT};
        server_name ${NGINX_HOST};
        root /usr/share/nginx/html;
        index index.html index.htm;

        location / {
            try_files $uri $uri/ /index.html =404;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
{{- end }}
{{- include "nginx.configMapTemplate" . | nindent 0 }}
