---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "robustName" .Release.Name  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- if or .Values.gitRepository .Values.gitSha }}
  annotations:
    {{- if .Values.gitRepository }}
    gimlet.io/git-repository: {{ .Values.gitRepository }}
    {{- end }}
    {{- if .Values.gitSha }}
    gimlet.io/git-sha: {{ .Values.gitSha }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}

{{- if .Values.externalService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalService.serviceName | default (printf "%s-external" (include "robustName" .Release.Name)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalService.name }}
  ports:
    - port: {{ .Values.externalService.port }}
      {{- if .Values.externalService.targetPort }}
      targetPort: {{ .Values.externalService.targetPort }}
      {{- end }}
      protocol: {{ .Values.externalService.protocol | default "TCP" }}
      name: "http"
{{- end }}
