{{- if and .Values.beeConfig.usePasswordFile (not .Values.beeConfig.existingSecret) -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bee.fullname" . }}
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
data:
    password: {{ include "bee.password" . | b64enc | quote }}
    
{{- end -}}