{{- $secretName := include "bee.databaseSecretName" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "bee.databaseSecretKey" . }}: |-
    {
      "port": {{ .Values.swarmProxy.database.port | quote }},
      "user": {{ .Values.swarmProxy.database.user | quote }},
      "host": {{ .Values.swarmProxy.database.host | quote }},
      "password": {{ .Values.swarmProxy.database.password | quote }},
      "database": {{ .Values.swarmProxy.database.name | quote }}
    }
