{{- if .Values.serviceAccount.create -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bee.serviceAccountName" . }}
  labels:
{{ include "bee.labels" . | nindent 4 }}

{{- end -}}
