{{- define "common.sealedSecret.tpl" -}}
  {{- if .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "common.robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
  {{- range $key, $val := .Values.sealedSecrets }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  template:
    metadata:
      name: {{ template "common.robustName" .Release.Name }}
      namespace: {{ .Release.Namespace }}
{{- end }}
{{- end -}}
