---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethexporter.fullname" . }}
  labels:
    {{- include "ethexporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ethexporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ethexporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ethexporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:      
        - name: ethexporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GETH
            value: "{{ .Values.ethexporter.gethEndpoint }}"
          - name: INTERVAL
            value: "{{ .Values.ethexporter.interval }}"
          - name: PORT
            value: "{{ .Values.service.port }}"
          ports:
            - name: metrics
              containerPort: {{ int .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.addressesTxt.enabled }}
          volumeMounts:
            - name: addresses-volume
              mountPath: /app/addresses.txt
              subPath: addresses.txt
          {{- end }}
          command:
            - ethexporter
      {{- if .Values.addressesTxt.enabled }}
      volumes:
        - name: addresses-volume
          configMap:
          {{- if not .Values.addressesTxt.addresses  }}
            name: {{ .Values.addressesTxt.existingConfigMap }}
          {{- else }}
            name: {{ include "ethexporter.fullname" . }}-addresses
            items:
            - key: addresses.txt
              path: addresses.txt
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
